import {MODELS,SOURCES,toChunks,retrieve,verifyAdmin,generateViaServer,requestServer,clean} from './ai-core.mjs?v=3';
const $=id=>document.getElementById(id),config=window.SAYEON_ANALYTICS_CONFIG||{};
let token=sessionStorage.getItem('sayeonAdminToken')||'',authorized=false,chunks=[],cache=new Map(),requests=0,controller=null,busy=false;
const text=(el,s)=>{el.textContent=s;};
function status(s,error=false){text($('status'),s);$('status').classList.toggle('error',error);}
function clearAll(){controller?.abort();chunks=[];cache.clear();['contentPassword','question'].forEach(id=>$(id).value='');$('freeOnly').checked=false;text($('answer'),'질문하면 여기에 결과가 나옵니다.');text($('evidence'),'관련 원문을 먼저 찾아보세요.');text($('corpusStatus'),'기존 등록 자료를 자동으로 확인합니다.');status('');}
async function check(){const current=sessionStorage.getItem('sayeonAdminToken')||'';if(!current||current!==token){authorized=false;clearAll();$('lab').classList.add('hidden');$('gate').classList.remove('hidden');throw new Error('관리자 로그인이 필요합니다.');}try{await verifyAdmin(config,current,fetch,controller?.signal);authorized=true;}catch(e){authorized=false;clearAll();$('lab').classList.add('hidden');$('gate').classList.remove('hidden');text($('gateMessage'),e.message);throw e;}}
function node(tag,s,cls){const el=document.createElement(tag);if(s!=null)el.textContent=s;if(cls)el.className=cls;return el;}
function link(doc){const a=node('a',doc.label+' · '+doc.title+' · '+(doc.pi+1)+'번째 문단');if(doc.url){a.href=doc.url;a.target='_blank';a.rel='noopener noreferrer';}return a;}
function showEvidence(found){$('evidence').replaceChildren();if(!found.length){text($('evidence'),'등록된 자료에서 질문에 맞는 근거를 찾지 못했습니다. 질문을 구체적으로 바꿔 주세요.');return;}found.forEach(doc=>{const box=node('details',null,'source');box.append(node('summary',doc.label+' · '+doc.title+' · '+(doc.pi+1)+'번째 문단'),node('p',doc.text),link(doc));$('evidence').append(box);});}
function showAnswer(result){$('answer').replaceChildren();if(!result.answer.supported){text($('answer'),'등록된 자료에서 답을 뒷받침할 근거를 찾지 못했습니다.');return;}$('answer').append(node('p',result.model+' · 인용 원문 확인','fine'));result.answer.claims.forEach(c=>{const box=node('article',null,'claim');box.append(node('span',c.kind==='inference'?'자료를 종합한 해석':'자료 근거 설명','badge'),node('p',c.text));c.sources.forEach(s=>{box.append(node('blockquote',s.quote),link(s.doc));});$('answer').append(box);});}
function evidenceForQuestion(){const q=$('question').value.trim();if(q.length<2)throw new Error('질문을 두 글자 이상 입력해 주세요.');if(!chunks.length)throw new Error('기존 등록 원고를 아직 열지 못했습니다. 아래 원고 암호 또는 연결 상태를 확인해 주세요.');return {q,found:retrieve(chunks,q,$('scope').value)};}
function setBusy(value){busy=value;['ask','preview','loadCorpus','unlock'].forEach(id=>$(id).disabled=value);$('cancel').disabled=!value;}
async function operation(fn){if(busy)return;controller=new AbortController();setBusy(true);const timeout=setTimeout(()=>controller?.abort(),60000);try{await check();await fn();}catch(e){status(e.name==='AbortError'?'요청을 중단했습니다. 원문 검색은 다시 사용할 수 있습니다.':e.message,true);}finally{clearTimeout(timeout);setBusy(false);controller=null;}}
async function load(){status('기존 등록 말씀·사연을 자동으로 확인하는 중…');if(!window.SaCrypt.ready()&&!await window.SaCrypt.resume()){$('unlockBox').classList.remove('hidden');text($('corpusStatus'),'기존 원고가 잠겨 있습니다. 앱에서 사용하던 원고 암호로 열면 등록 자료 전체에서 검색합니다.');status('새 자료 업로드 없이 기존 원고를 사용합니다.');return;}const results=await Promise.allSettled(SOURCES.map(async source=>toChunks(await window.SaCrypt.json(source.url),source)));if(controller.signal.aborted||!authorized)return;const docs=[],ok=[],failed=[];results.forEach((r,i)=>{if(r.status==='fulfilled'){docs.push(...r.value);ok.push(SOURCES[i].label+': '+r.value.length+'문단');}else failed.push(SOURCES[i].label);});chunks=docs;cache.clear();$('unlockBox').classList.add('hidden');$('contentPassword').value='';text($('corpusStatus'),ok.join(' / ')+(failed.length?'\n불러오지 못한 자료: '+failed.join(', '):'')+'\n총 '+chunks.length+'문단 · 새 원고는 화면 새로고침 시 자동 반영');status(failed.length?'일부 자료를 불러오지 못했습니다. 불러온 자료만 검색합니다.':'기존 등록 자료에서 바로 질문할 수 있습니다.',!!failed.length);}
$('loadCorpus').onclick=()=>operation(load);
$('unlock').onclick=()=>operation(async()=>{if(!await window.SaCrypt.unlock($('contentPassword').value))throw new Error('원고 암호를 확인해 주세요.');await load();});
async function serverInfo(){try{const d=await requestServer(config,token,{action:'status'},fetch,controller?.signal);if(d.ready!==true||!Array.isArray(d.models))throw new Error('서버 연결 응답을 확인하지 못했습니다.');text($('serverStatus'),'서버 연결됨 · 키는 Supabase에만 보관됩니다.');document.querySelectorAll('#model option').forEach(o=>{if(o.value!=='search')o.disabled=!d.models.includes(o.value);});if(d.quota)text($('usage'),'오늘 서버 호출: '+d.quota.used+'회 · 남은 테스트 호출: '+d.quota.remaining+'회');}catch(e){text($('serverStatus'),e.message+' 원문 검색은 계속 사용할 수 있습니다.');}}
$('serverCheck').onclick=()=>operation(serverInfo);
$('model').onchange=()=>{$('keyBox').classList.toggle('hidden',$('model').value==='search');};
$('preview').onclick=()=>operation(async()=>{const {found}=evidenceForQuestion();showEvidence(found);text($('answer'),'원문 검색 결과입니다. AI 답변을 생성하지 않았습니다.');status(found.length+'개 관련 문단 · API 사용 없음');});
$('ask').onclick=()=>operation(async()=>{
 const {q,found}=evidenceForQuestion();showEvidence(found);text($('answer'),'');if(!found.length){text($('answer'),'등록된 자료에서 답을 찾지 못했습니다.');status('근거 부족 · AI를 호출하지 않았습니다.');return;}
 const modelId=$('model').value;if(modelId==='search'){text($('answer'),'아래 검색 결과에서 원문과 출처를 확인해 주세요.');status('원문 검색만 실행 · API 사용 없음');return;}
 if(!$('freeOnly').checked)throw new Error('결제를 연결하지 않은 무료 등급 API 키인지 먼저 확인해 주세요.');const model=MODELS[modelId];if(!model)throw new Error('모델을 선택해 주세요.');
 const ck=JSON.stringify([modelId,clean(q),$('scope').value,found.map(c=>[c.id,c.text])]);if($('useCache').checked&&cache.has(ck)){showAnswer(cache.get(ck));status('이 화면에 저장된 동일 질문 답변 재사용 · 새 API 호출 없음');return;}
 status(model.label+' 답변 생성 중…');requests++;text($('usage'),'이 화면에서 시도한 AI 요청: '+requests+'회 · 실제 남은 한도는 업체 콘솔에서 확인');
 let result;try{result=await generateViaServer(config,token,modelId,q,found,true,fetch,controller.signal);}catch(e){if(e instanceof TypeError)throw new Error('관리자 AI 서버에 연결하지 못했습니다. 서버 연결 상태를 확인해 주세요.');throw e;}
 if(controller.signal.aborted||!authorized)return;showAnswer(result);cache.set(ck,result);if(result.quota)text($('usage'),'오늘 서버 호출: '+result.quota.used+'회 · 남은 테스트 호출: '+result.quota.remaining+'회');status('완료 · 원문 인용 검사 통과'+(result.usage?' · 토큰 정보: '+JSON.stringify(result.usage):''));
});
$('cancel').onclick=()=>controller?.abort();$('clear').onclick=()=>{controller?.abort();cache.clear();['question'].forEach(id=>$(id).value='');$('freeOnly').checked=false;text($('answer'),'질문하면 여기에 결과가 나옵니다.');text($('evidence'),'관련 원문을 먼저 찾아보세요.');status('답변을 지웠습니다. 기존 등록 자료는 그대로 검색할 수 있습니다.');};$('logout').onclick=()=>{authorized=false;clearAll();sessionStorage.removeItem('sayeonAdminToken');token='';location.href='./';};document.querySelectorAll('.example').forEach(b=>b.onclick=()=>{$('question').value=b.textContent;});window.addEventListener('pagehide',()=>{authorized=false;clearAll();});
try{await check();$('gate').classList.add('hidden');$('lab').classList.remove('hidden');await operation(async()=>{await load();await serverInfo();});}catch(e){text($('gateMessage'),e.message);}
