"""Bundle the password/admin authenticated Edge Function into a dashboard-deployable file."""
from pathlib import Path
import re
root = Path(__file__).resolve().parents[1]
core = (root / 'admin/ai-core.mjs').read_text()
handler = (root / 'supabase/functions/admin-ai/handler.mjs').read_text()
handler = re.sub(r'^import .*?;\n', '', handler, count=1)
(root / 'supabase/functions/admin-ai/index.ts').write_text(
    '// Generated by tools/build_admin_ai.py. Do not edit this file alone.\n'
    + core + '\n' + handler
    + '\nDeno.serve(createHandler({env:name=>Deno.env.get(name)}));\n'
)
